export const CHANGE_FILTER = 'CHANGE_FILTER';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
